[tools]
swiftlint = "0.62.2"
tuist = "4.109.1"
periphery = "3.2.0"
pre-commit = "4.5.0"
node = "24.11.1"

[tasks.bump-tools]
description = "Bump all tool versions to the latest"
run = "mise upgrade --bump && uv run pre-commit autoupdate && pnpm update --recursive"
